POST http://localhost:3333/videos
Content-type: application/json


{
    "title": "Video node",
    "description": "teste",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/122da6a0-af6d-4bcc-bf6f-09b88dbd2816
Content-type: application/json


{
    "title": "Video node",
    "description": "vido de update",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/122da6a0-af6d-4bcc-bf6f-09b88dbd2816
